apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: nodeapp
        image: 596953737188.dkr.ecr.ap-south-1.amazonaws.com/dev/devopsified
        ports:
        - containerPort: 3000
